ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'NOT_ELIGIBLE';
ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'RATE_LIMITED';
ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'TIMEOUT';
ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'NETWORK_ERROR';
ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'SERVER_ERROR';
ALTER TYPE "AnimeTitleLookupStatus" ADD VALUE IF NOT EXISTS 'CLIENT_ERROR';
